version: 2
updates:
  # JavaScript dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'vitest*'
          - 'typescript'
        update-types:
          - 'minor'
          - 'patch'
      production-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
          - 'vitest*'
          - 'typescript'
        update-types:
          - 'patch'
    ignore:
      # Major versions we'll update manually
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    groups:
      github-actions:
        patterns:
          - '*'

  # Docker dependencies in docker-compose files
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    ignore:
      # Keep postgres and redis versions stable
      - dependency-name: 'postgres'
        update-types: ['version-update:semver-major']
      - dependency-name: 'redis'
        update-types: ['version-update:semver-major']
