name: pika_app
description: A modern marketplace platform for service providers and customers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2

  # Firebase Auth Providers
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # Local Storage & Offline Support
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # UI & Design
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.14
  shimmer: ^3.0.0
  badges: ^3.1.2
  flutter_native_splash: ^2.4.1
  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^15.1.3

  # Utilities
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  collection: ^1.18.0
  dartz: ^0.10.1

  # Platform-specific
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.1
  image_picker: ^1.1.2

  # Other
  logger: ^2.4.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  device_info_plus: ^11.4.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1

  # Security & Performance
  local_auth: ^2.3.0
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  retrofit_generator: ^9.2.0
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0

  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  patrol: ^3.11.0

  # Analysis
  analyzer: ^6.11.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/gen/
  line_length: 120

  integrations:
    flutter_svg: true
# flutter_native_splash:
#   color: "#2196F3"
#   image: assets/images/splash_logo.png
#   android: true
#   ios: true
#   web: true
